### ISSUE TITLE
Steam Login proxy error

### ISSUE THREAD

**Issue by QLthund3rbolt** [vgoskins/vcase#23]
Hello. Soo i wanted to test this site out on my localhost. Site came up and once i clicked on steam login this error message came up:
Proxy error: Could not proxy request /auth from localhost:3000 to http://localhost:3001/.
[1] [HPM] Error occurred while trying to proxy request /auth from localhost:3000 to http://localhost:3001/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
i downloaded the whole project and did npm to all package folders. and then run the project by npm start.
Im testing it on windows 10 using node 8.11.03 and npm. Im glad if you guys could help me out!!!

**Comment by skylight-ity** [comment]
Try running without port, meaning you can run on port 80

**Comment by QLthund3rbolt** [comment]
Well i got finally it work on windows development XD steam id was missing thats why it gave me that rpxoy error....For windows i needed to edit package json.Now it all good xD
