### ISSUE TITLE
Not Found Error

### ISSUE THREAD

**Issue by KronosR97** [vgoskins/vcase#7]
Hello!

Well, im trying to run the script in production mode but i cant, im getting "Not Found" error on the screen, i just test it in dev mode and works good, i dont understand what is going on...

Website error https://i.gyazo.com/7821b9081c197cac6fd765c09cccef17.png
Console https://i.imgur.com/fd0EjZP.png

i hope someone can help me

Im using node 8.9.4 by the way

**Comment by Gergo4961** [comment]
Hey!

Check the guides they have linked on the bottom of the readme file, you are missing out on important steps to create a react app, it's simple though:

npm i -g create-react-app

create-react-app FOLDERNAME

And then you just do all the other steps again in that folder, it should work then!

**Comment by KronosR97** [comment]
Thanks @Gergo4961 it worked, now i have another issue, when i login i got this error

https://i.gyazo.com/10571b062c918306896e79b37bfdcb14.png
